version: '3.9'

services:

  mysql-kc:
    container_name: mysql-kc
    image: mysql:8.0.27
    ports:
      - 3307:3306
    restart: unless-stopped
    environment:
      MYSQL_USER: tipikae
      MYSQL_PASSWORD: 231045
      MYSQL_DATABASE: keycloak
      MYSQL_ROOT_PASSWORD: root
    cap_add:
      - SYS_NICE
    volumes:
      - keycloak-and-mysql-volume:/var/lib/mysql
    networks:
      - keycloak-and-mysql-network
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 30s
      timeout: 10s
      retries: 5

  keycloak-w:
    container_name: keycloak
    build: ./keycloak
    image: keycloak
    ports:
      - 8070:8080
    restart: unless-stopped
    environment:
      JDBC_PARAMS: useSSL=false&allowPublicKeyRetrieval=true
    depends_on:
      mysql-kc:
        condition: service_healthy
    networks:
      - keycloak-and-mysql-network

networks:
  keycloak-and-mysql-network:

volumes:
  keycloak-and-mysql-volume: