version: '3.9'

services:

  keycloak-db:
    container_name: keycloak-db
    image: mysql:8.0.27
    ports:
      - 3307:3306
    restart: on-failure
    environment:
      MYSQL_USER: tipikae
      MYSQL_PASSWORD: 231045
      MYSQL_DATABASE: keycloak
      MYSQL_ROOT_PASSWORD: root
    cap_add:
      - SYS_NICE
    volumes:
      - keycloak-db:/var/lib/mysql
    networks:
      - mediscreen-network
      
  patient-db:
    container_name: patient-db
    image: mysql:8.0.27
    ports:
      - 3308:3306
    restart: on-failure
    environment:
      MYSQL_USER: tipikae
      MYSQL_PASSWORD: 231045
      MYSQL_DATABASE: mediscreen
      MYSQL_ROOT_PASSWORD: root
    cap_add:
      - SYS_NICE
    volumes:
      - patient-db:/var/lib/mysql
    networks:
      - mediscreen-network
      
  note-db:
    container_name: note-db
    image: mongo:latest
    restart: on-failure
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: tipikae
      MONGO_INITDB_ROOT_PASSWORD: 231045
      MONGO_INITDB_DATABASE: mediscreen
    volumes:
      - ./mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - note-db:/var/lib/mongodb
    networks:
      - mediscreen-network
      
  assessment-db:
    container_name: assessment-db
    image: mysql:8.0.27
    ports:
      - 3309:3306
    restart: on-failure
    environment:
      MYSQL_USER: tipikae
      MYSQL_PASSWORD: 231045
      MYSQL_DATABASE: mediscreen
      MYSQL_ROOT_PASSWORD: root
    cap_add:
      - SYS_NICE
    volumes:
      - assessment-db:/var/lib/mysql
    networks:
      - mediscreen-network
       
  config-service:
    container_name: config-service
    build: ./mediscreen-config
    image: config
    ports:
      - 8888:8888
    restart: on-failure
    networks:
      - mediscreen-network
       
  eureka-server:
    container_name: eureka-server
    build: ./mediscreen-discovery
    image: eureka
    ports:
      - 8761:8761
    restart: on-failure
    environment:
      - SPRING_CONFIG_IMPORT=configserver:http://config-service:8888
    networks:
      - mediscreen-network
      
  gateway-service:
    container_name: gateway-service
    build: ./mediscreen-proxy
    image: proxy
    ports:
      - 8080:8080
    restart: on-failure
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      #- SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI=http://keycloak-service:8080/realms/mediscreen
      - SPRING_CONFIG_IMPORT=configserver:http://config-service:8888
    networks:
      - mediscreen-network

  keycloak-service:
    container_name: keycloak-service
    build: ./keycloak
    image: keycloak
    ports:
      - 8070:8080
    restart: on-failure
    environment:
      JDBC_PARAMS: useSSL=false&allowPublicKeyRetrieval=true
    networks:
      - mediscreen-network
      
  patient-service:
    container_name: patient-service
    build: ./patient-service
    image: patientservice
    restart: on-failure
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://patient-db:3306/mediscreen?enabledTLSProtocols=TLSv1.2
      - SPRING_CONFIG_IMPORT=configserver:http://config-service:8888
    networks:
      - mediscreen-network
      
  note-service:
    container_name: note-service
    build: ./note-service
    image: noteservice
    restart: on-failure
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATA_MONGODB_HOST=note-db
      - SPRING_CONFIG_IMPORT=configserver:http://config-service:8888
    networks:
      - mediscreen-network
      
  assessment-service:
    container_name: assessment-service
    build: ./assessment-service
    image: assessmentservice
    restart: on-failure
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://assessment-db:3306/mediscreen?enabledTLSProtocols=TLSv1.2
      - SPRING_CONFIG_IMPORT=configserver:http://config-service:8888
    networks:
      - mediscreen-network
      
  frontend:
    container_name: frontend
    build: ./mediscreen-UI
    image: frontend
    ports:
      - 8090:8090
    restart: on-failure
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CONFIG_IMPORT=configserver:http://config-service:8888
    networks:
      - mediscreen-network

networks:
  mediscreen-network:

volumes:
  keycloak-db:
  patient-db:
  note-db:
  assessment-db:
