version: '3.9'

services:

  mysql-kc:
    container_name: mysql-kc
    image: mysql:8.0.27
    ports:
      - 3307:3306
    restart: on-failure
    environment:
      MYSQL_USER: tipikae
      MYSQL_PASSWORD: 231045
      MYSQL_DATABASE: keycloak
      MYSQL_ROOT_PASSWORD: root
    cap_add:
      - SYS_NICE
    volumes:
      - mediscreen-volume:/var/lib/mysql
    networks:
      - mediscreen-network
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 30s
      timeout: 10s
      retries: 5

  keycloak:
    container_name: keycloak
    build: .
    image: keycloak
    ports:
      - 8070:8080
    restart: on-failure
    environment:
      JDBC_PARAMS: useSSL=false&allowPublicKeyRetrieval=true
    depends_on:
      mysql-kc:
        condition: service_healthy
    networks:
      - mediscreen-network
      
  mysql-patient:
    container_name: mysql-patient
    image: mysql:8.0.27
    ports:
      - 3308:3306
    restart: on-failure
    environment:
      MYSQL_USER: tipikae
      MYSQL_PASSWORD: 231045
      MYSQL_DATABASE: mediscreen
      MYSQL_ROOT_PASSWORD: root
    cap_add:
      - SYS_NICE
    volumes:
      - mediscreen-volume:/var/lib/mysql
    networks:
      - mediscreen-network
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 30s
      timeout: 10s
      retries: 5
      
  patient:
    container_name: patient
    build: ./patient-service
    image: patientservice
    restart: on-failure
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    healthcheck:
      test: "curl --fail --silent localhost:8081/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s
    depends_on:
      mysql-patient:
        condition: service_healthy
    networks:
      - mediscreen-network
      
  mongo-note:
    container_name: mongo-note
    image: mongo:latest
    restart: on-failure
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: tipikae
      MONGO_INITDB_ROOT_PASSWORD: 231045
      MONGO_INITDB_DATABASE: mediscreen
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - mediscreen-volume:/var/lib/mongodb
    networks:
      - mediscreen-network
      
  note:
    container_name: note
    build: ./note-service
    image: noteservice
    restart: on-failure
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    healthcheck:
      test: "curl --fail --silent localhost:8082/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s
    depends_on:
      mongodb-note:
        condition: service_healthy
    networks:
      - mediscreen-network
      
  assessment:
    container_name: assessment
    build: ./assessment-service
    image: assessmentservice
    restart: on-failure
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    healthcheck:
      test: "curl --fail --silent localhost:8083/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s
    depends_on:
      note:
        condition: service_healthy
      patient:
        condition: service_healthy
    networks:
      - mediscreen-network

networks:
  mediscreen-network:

volumes:
  mediscreen-volume:
  mongodb-volume:
